/*
    Compile unit: C:\rockband2\system\src\cntsdrso\cntsdrso.inc
    Producer: MW EABI PPC C-Compiler
    Language: C++
    Code range: 0x805AC1F4 -> 0x805AC2B4
*/
// Range: 0x805AC1F4 -> 0x805AC204
static void unresolved_cntsdModule() {}

// Range: 0x805AC204 -> 0x805AC27C
static void ResolvedModule_cntsdModule(const struct RSOObjectHeader * module /* r28 */) {
    // Local variables
    int i; // r29

    // References
    // -> static struct RSOExportFuncTable exp_tbl_cntsdModule[14];
}

// Range: 0x805AC27C -> 0x805AC2B4
static void UnresolvedModule_cntsdModule() {
    // Local variables
    int i; // r5

    // References
    // -> static struct RSOExportFuncTable exp_tbl_cntsdModule[14];
}


