object: orig/SZBE69/sys/main.dol
hash: 189b001188a2f8ab769e72364440022407fe09d2
splits: config/SZBE69/splits.txt
symbols: config/SZBE69/symbols.txt
selfile: orig/SZBE69/files/band_s_wii.sel
selfile_hash: ca902f87c70f57b140b411d5946341c13d7616cf
mw_comment_version: 14
quick_analysis: true
