/*
    Compile unit: C:\rockband2\system\src\zlib\zlib.inc
    Producer: MW EABI PPC C-Compiler
    Language: C++
    Code range: 0x806083B8 -> 0x80608478
*/
// Range: 0x806083B8 -> 0x806083C8
static void unresolved_zlibModule() {}

// Range: 0x806083C8 -> 0x80608440
static void ResolvedModule_zlibModule(const struct RSOObjectHeader * module /* r28 */) {
    // Local variables
    int i; // r29

    // References
    // -> static struct RSOExportFuncTable exp_tbl_zlibModule[6];
}

// Range: 0x80608440 -> 0x80608478
static void UnresolvedModule_zlibModule() {
    // Local variables
    int i; // r5

    // References
    // -> static struct RSOExportFuncTable exp_tbl_zlibModule[6];
}


