object: orig/SZBE69_B8/sys/main.dol
symbols: config/SZBE69_B8/symbols.txt
splits: config/SZBE69_B8/splits.txt
selfile: orig/SZBE69_B8/files/band_r_wii.sel
mw_comment_version: 14
quick_analysis: true

block_relocations:
  # False relocations in binkacd due to funky bit arithmetic
- source: .text:0x80A1A9D0 # ClampToS16
  end: .text:0x80A1AA3C
- source: .text:0x80A1AA40 # ClampToS16AndInterleave
  end: .text:0x80A1AAF8
  # False relocations in ChecksumData_wii
- source: .data:0x80B585D4
- source: .data:0x80B58EC4
- source: .data:0x80B5ADB8
- source: .data:0x80B5B3A0
- source: .data:0x80B5B714
- source: .data:0x80B5BCF8
- source: .data:0x80B5BED4
- source: .data:0x80B5C1F0
- source: .data:0x80B5D0AC
