object: orig/SZBE69_B8/sys/main.dol
symbols: config/SZBE69_B8/symbols.txt
splits: config/SZBE69_B8/splits.txt
selfile: orig/SZBE69_B8/files/band_r_wii.sel
mw_comment_version: 14
quick_analysis: true

block_relocations:
  # False relocations in binkacd due to funky bit arithmetic
- source: .text:0x80A1A9D0 # ClampToS16
  end: .text:0x80A1AA3C
- source: .text:0x80A1AA40 # ClampToS16AndInterleave
  end: .text:0x80A1AAF8
  # False relocations in ChecksumData_wii
- source: .data:0x80B585D4
- source: .data:0x80B58EC4
- source: .data:0x80B5ADB8
- source: .data:0x80B5B3A0
- source: .data:0x80B5B714
- source: .data:0x80B5BCF8
- source: .data:0x80B5BED4
- source: .data:0x80B5C1F0
- source: .data:0x80B5D0AC
  # False relocations in MSL_C string.c
- source: .text:0x80A2F060 # strcpy
  end: .text:0x80A2F064
- source: .text:0x80A2F208 # strcmp
  end: .text:0x80A2F20C

add_relocations:
- source: .text:0x8000eba0
  type: l
  target: TheLoadMgr
- source: .text:0x8000ed40
  type: l
  target: TheLoadMgr
- source: .text:0x8000ef30
  type: l
  target: TheLoadMgr
- source: .text:0x8000f578
  type: l
  target: TheLoadMgr
- source: .text:0x8000f784
  type: l
  target: TheLoadMgr
- source: .text:0x8017371c
  type: l
  target: TheLoadMgr
- source: .text:0x80173a94
  type: l
  target: TheLoadMgr
- source: .text:0x80173be4
  type: l
  target: TheLoadMgr
- source: .text:0x80484d04
  type: l
  target: TheLoadMgr
- source: .text:0x807c8968
  type: l
  target: TheLoadMgr
- source: .text:0x807c897c
  type: l
  target: __RTTI__10UILabelDir
- source: .text:0x807c8980
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807c8b08
  type: l
  target: TheLoadMgr
- source: .text:0x807c8b1c
  type: l
  target: __RTTI__10UILabelDir
- source: .text:0x807c8b20
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f0150
  type: l
  target: TheLoadMgr
- source: .text:0x807f0164
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f0168
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f0448
  type: l
  target: TheLoadMgr
- source: .text:0x807f045c
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f0460
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f0700
  type: l
  target: TheLoadMgr
- source: .text:0x807f0714
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f0718
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f0d18
  type: l
  target: TheLoadMgr
- source: .text:0x807f0d2c
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f0d30
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f1218
  type: l
  target: TheLoadMgr
- source: .text:0x807f122c
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f1230
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f1a5c
  type: l
  target: TheLoadMgr
- source: .text:0x807f1a70
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f1a74
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f1c60
  type: l
  target: TheLoadMgr
- source: .text:0x807f1c74
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f1c78
  type: l
  target: __RTTI__9ObjectDir
- source: .text:0x807f2ce0
  type: l
  target: TheLoadMgr
- source: .text:0x807f2cf4
  type: l
  target: __RTTI__6RndDir
- source: .text:0x807f2cf8
  type: l
  target: __RTTI__9ObjectDir
